/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EventPlatformAbi } from "./EventPlatformAbi";

export { EventPlatformAbi__factory } from "./factories/EventPlatformAbi__factory";
